---
title: "Research"
description: |
  Most of my research centers on human memory, focusing collective memory, how face-to-face and online collaboration influences memory, and the relationship between collective memory and retrieval dynamics.
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Publications

$^{*}$ *Indicates first authorship*

**Greeley, G. D.**$^{*}$, Peña, T., Pepe, N. W., Choi, H-Y., & Rajaram, S. (In Prep). Collective Memory for U.S. Cities: A Striking Stability in Recall Through a Period of Upheaval.

Jin, J., Choi, H-Y., Pepe, N. W., **Greeley, G. D.**, Kensinger, E. A., Mohanty, A., & Rajaram, S. (In Prep). Assessing the Global Structure of Collective Memory: Application of the Representational Similarity Analysis.

**Greeley, G. D.**$^{*}$ & Rajaram, S. (Under Review). Collective Memory: Collaborative Recall Synchronizes What and How People Remember. *Manuscript Submitted & Under Review*.

**Greeley, G. D.**$^{*}$, Chan, V., Choi, H-Y., & Rajaram, S. (Under Review). Collaborative Recall and the Construction of Collective Memory Organization: The Impact of Group Structure. *Manuscript Submitted & Under Review*.

**Greeley, G. D.**$^{*}$, Peña, T.$^{*}$, & Rajaram, S. (2022). Social Remembering in the Digital Age: Implications for Virtual Study, Work, and Social Engagement. *Memory, Mind & Media*, *1(e13)*. 1-23. [https://doi.org/10.1017/mem.2022.3](https://doi.org/10.1017/mem.2022.3)

Rajaram, S., Peña, T., & **Greeley, G. D.** (2022). *How Collective Memories Emerge: A Cognitive Psychological Perspective*. In H. L. Roediger & J. Wertsch (Eds.), National Memories: Constructing Identity in Populist Times. Oxford: Academic Press. [Available here](https://global.oup.com/academic/product/national-memories-9780197568675?q=National%20Memories:%20Constructing%20Identity%20in%20Populist%20Times&cc=us&lang=en#)

# Posters & Talks

**Greeley, G. D.**$^{*}$, Chan, V., Choi, H-Y., & Rajaram, S. (2022; Submitted). Collaborative Recall and the Construction of Collective Memory Organization: The Impact of Group Structure. *Accepted for a poster presentation at the 63rd Annual Meeting of the Psychonomic Society – Boston, MA*.

\vspace{4pt}

\begin{hangingpar}{2em}
Chan, V., **Greeley, G. D.**, & Rajaram, S. (2022). How Does Recalling the Past with the Same versus Different Conversational Partners Shape our Collective Memory Structures?: A Secondary Data Analysis. *Presented as a poster at Stony Brook University's URECA Conference – Stony Brook, NY.* 

**Greeley, G. D.**$^{*}$, Peña, T., Pepe, N. W., Choi, H-Y., & Rajaram, S. (2021). Collective Memory for U.S. Cities: A Striking Stability in Recall Through a Period of Upheaval. *Presented as a poster at the 62nd Annual Meeting of the Psychonomic Society – Virtual.*

Jin, J., Choi, H-Y., Pepe, N. W., **Greeley, G. D.**, Kensinger, E. A., Mohanty, A., & Rajaram, S. (2021). Assessing the Global Structure of Collective Memory: Application of the Representational Similarity Analysis. *Presented as a poster at the 62nd Annual Meeting of the Psychonomic Society – Virtual.*

**Greeley, G. D.**$^{*}$, Peña, T.$^{*}$, & Rajaram, S. (2021). Collaborative Remembering in a Fully Online, Chat-Based Environment: Implications for Remote Study and Work. *Presented as a poster at the 62nd Annual Meeting of the Psychonomic Society – Virtual.*

**Greeley, G. D.**$^{*}$, Peña, T.$^{*}$, & Rajaram, S. (2021). Collaborative Remembering in a Fully Online, Chat-Based Environment: Implications for Remote Study and Work. *Presented at Stony Brook University’s Cognitive Science Area 2nd/4th Year Symposium – Virtual.*

Smith, E., **Greeley, G. D.**, & Russell, E. (2019). Correspondence bias: Gender effects across temporal scales. *Poster presented at the 2019 Midwestern Psychological Association (MPA) Conference – Chicago, IL.*

**Greeley, G. D.** (2018). Predictive processing effects in visual working memory? *Poster presented at Winona State University’s 12th Annual Ramaley Research Celebration – Winona, MN.*

**Greeley, G. D.** (2018). Predictive processing effects in visual working memory? *Poster presented at the Minnesota Undergraduate Psychology Conference (MUPC) - Carleton College, Northfield, MN.*

“Actualizing Activism” Course Group. (2016). Mental health on campus: Raising awareness and reducing stigma.
Organized presentation and panel discussion at Gustavus Adolphus College, St. Peter, MN.


