---
title: "Teaching"
description: |
  At Stony Brook, I've been both a teaching assistant and a lab instructor for several undergraduate and graduate-level courses.
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# 2022

<center><font size="4"> **Fall**</font></center>

**Teaching Assistant** $-$ "Memory"

This was an undergraduate course, primarily for psychology majors. Responsible for helping with discussion, grading homework and papers, preparing exams, and holding regular office hours.

Students: $\approx 100$ undergraduates

<center><font size="4"> **Spring**</font></center>

*Did not teach spring 2022*: I was moved to a Research Assistant funding line for an academic year, starting August 2021. During this semester, I focused on research and co-mentored an undergraduate honors thesis.

---

# 2021

<center><font size="4"> **Fall**</font></center>

*Did not teach fall 2021*: I was moved to a Research Assistant funding line for an academic year, starting August 2021. During this semester, I focused on research and co-mentored an undergraduate honors thesis.

<center><font size="4"> **Spring**</font></center>

**Lab Instructor** $-$ "Introduction to Computer Applications in Statistics"

This was a graduate-level statistics course focused on using R for data analysis, especially correlation/regression fundamentals. Responsible for giving regular lab-based lectures (including live-coding) and grading.

Students: $\approx 20$ graduate students

---

# 2020

<center><font size="4"> **Fall**</font></center>

**Lab Instructor** $-$ "Research and Writing for Psychology"

This was an upper-level undergraduate course focused on research methods and scientific writing in psychology. Responsible for weekly lab-based lectures, grading, and leading students through each stage of a novel research proposal, from design to write-up.

Students: $\approx 25$ undergraduates

<center><font size="4"> **Spring**</font></center>

**Teaching Assistant** $-$ "Statistical Methods in Psychology"

This was an undergraduate course, primarily for psychology majors. Responsible for helping with in-class activities, proctoring exams, and holding regular office hours.

Students: $\approx 200$ undergraduates

---

# 2019

<center><font size="4"> **Fall**</font></center>

**Teaching Assistant** $-$ "Introduction to Psychology"

This was a large, general undergraduate course. Responsible for proctoring exams and holding regular office hours.

Students: $\approx 550$ undergraduates

---

# 2017

<center><font size="4"> **Fall**</font></center>

**Teaching Assistant** $-$ "Cognitive Psychology"

While still an undergraduate at Winona State University, I was a TA for a small undergraduate course. Responsible for helping with in-class activities, proctoring exams, and developing some course content (e.g., additional slides that cover research on a given theme).

Students: $\approx 20$ undergraduates 

